"""
TrustHire AI — PDF report generation service.
Uses Jinja2 for HTML templating and WeasyPrint for PDF conversion.
"""

import logging
import os
import uuid
from datetime import datetime
from pathlib import Path

logger = logging.getLogger(__name__)

TEMPLATE_DIR = Path(__file__).parent / "templates"
TEMPLATE_DIR.mkdir(parents=True, exist_ok=True)

DISCLAIMER = (
    "This report is generated by TrustHire AI for informational purposes only. "
    "All public record matches are potential matches requiring manual review by a "
    "qualified compliance officer. This report does not constitute legal advice and "
    "must not be used as the sole basis for any hiring decision. "
    "Employment decisions based solely on automated background checks may be unlawful."
)

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, Helvetica, sans-serif; font-size: 11pt; color: #1a1a1a; }
  .header { background: #1e40af; color: #fff; padding: 24px 36px; }
  .header h1 { font-size: 18pt; font-weight: 700; margin-bottom: 4px; }
  .header p { font-size: 9.5pt; opacity: .8; }
  .body { padding: 28px 36px; }
  .section { margin-bottom: 24px; }
  .section-title {
    font-size: 12pt; font-weight: 700; border-bottom: 2px solid #e5e7eb;
    padding-bottom: 5px; margin-bottom: 12px; color: #1e3a8a;
  }
  table { width: 100%; border-collapse: collapse; margin-bottom: 10px; }
  td, th { padding: 7px 10px; border-bottom: 1px solid #f3f4f6; font-size: 10pt; }
  th { background: #f9fafb; font-weight: 600; width: 36%; }
  .risk-badge { display: inline-block; padding: 3px 12px; border-radius: 20px; font-size: 10pt; font-weight: 600; }
  .risk-low      { background: #dcfce7; color: #166534; }
  .risk-medium   { background: #fef9c3; color: #854d0e; }
  .risk-high     { background: #ffedd5; color: #9a3412; }
  .risk-critical { background: #fee2e2; color: #991b1b; }
  .card { border: 1px solid #e5e7eb; border-radius: 7px; padding: 12px 16px; margin-bottom: 10px; }
  .card-title { font-weight: 600; font-size: 10.5pt; }
  .card-sub { color: #6b7280; font-size: 9.5pt; margin-top: 2px; }
  .status { font-weight: 600; font-size: 9.5pt; margin-top: 5px; }
  .status-verified   { color: #16a34a; }
  .status-unverified { color: #dc2626; }
  .status-pending    { color: #d97706; }
  .status-email_sent { color: #2563eb; }
  .flag-card { border-left: 4px solid #f59e0b; padding: 9px 14px; margin-bottom: 8px; background: #fffbeb; }
  .flag-high, .flag-critical { border-left-color: #ef4444; background: #fef2f2; }
  .reasoning-box { background: #f8fafc; border-radius: 6px; padding: 12px 14px; font-size: 10pt; line-height: 1.7; color: #374151; margin-top: 10px; }
  .disclaimer { font-size: 8.5pt; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 12px; margin-top: 24px; line-height: 1.6; }
  .score-grid { display: grid; grid-template-columns: repeat(5, 1fr); gap: 8px; margin: 12px 0; }
  .score-cell { text-align: center; border: 1px solid #e5e7eb; border-radius: 6px; padding: 8px 4px; }
  .score-num { font-size: 18pt; font-weight: 700; color: #1e40af; }
  .score-label { font-size: 8pt; color: #6b7280; margin-top: 2px; }
</style>
</head>
<body>
<div class="header">
  <h1>Verification Report — {{ candidate_name }}</h1>
  <p>Generated by TrustHire AI &nbsp;·&nbsp; {{ generated_at }}</p>
</div>
<div class="body">

  <!-- SUMMARY -->
  <div class="section">
    <div class="section-title">Summary</div>
    <table>
      <tr><th>Candidate</th><td>{{ candidate_name }}</td></tr>
      <tr><th>Verification status</th><td>{{ status | title | replace('_', ' ') }}</td></tr>
      <tr><th>Overall risk score</th><td>
        <span class="risk-badge risk-{{ risk_level }}">
          {{ risk_score }}/100 — {{ risk_level | title }}
        </span>
      </td></tr>
      <tr><th>Confidence</th><td>{{ confidence }}%</td></tr>
    </table>
    {% if ai_reasoning %}
    <div class="reasoning-box">{{ ai_reasoning }}</div>
    {% endif %}
  </div>

  <!-- SCORE BREAKDOWN -->
  {% if breakdown %}
  <div class="section">
    <div class="section-title">Score Breakdown</div>
    <div class="score-grid">
      {% for key, val in breakdown.items() %}
      <div class="score-cell">
        <div class="score-num">{{ val.score }}</div>
        <div class="score-label">{{ key | replace('_', ' ') | title }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
  {% endif %}

  <!-- EMPLOYMENT -->
  <div class="section">
    <div class="section-title">Employment Verification</div>
    {% if employment %}
      {% for emp in employment %}
      <div class="card">
        <div class="card-title">{{ emp.job_title or 'Role not specified' }} — {{ emp.company_name }}</div>
        <div class="card-sub">{{ emp.start_date or '?' }} → {{ emp.end_date or 'Present' }}{% if emp.location %} &nbsp;·&nbsp; {{ emp.location }}{% endif %}</div>
        <div class="status status-{{ emp.verification_status }}">
          Status: {{ emp.verification_status | replace('_', ' ') | title }}
          {% if emp.confidence_score %} · Confidence: {{ emp.confidence_score }}%{% endif %}
        </div>
        {% if emp.notes %}<div style="font-size:9.5pt;color:#4b5563;margin-top:5px;">{{ emp.notes }}</div>{% endif %}
      </div>
      {% endfor %}
    {% else %}
      <p style="color:#6b7280;font-size:10pt;">No employment records found.</p>
    {% endif %}
  </div>

  <!-- EDUCATION -->
  <div class="section">
    <div class="section-title">Education Verification</div>
    {% if education %}
      {% for edu in education %}
      <div class="card">
        <div class="card-title">{{ edu.degree or 'Qualification' }}{% if edu.field_of_study %} in {{ edu.field_of_study }}{% endif %}</div>
        <div class="card-sub">{{ edu.institution_name }} · {{ edu.graduation_year or '?' }}</div>
        <div class="status status-{{ edu.verification_status }}">
          Status: {{ edu.verification_status | replace('_', ' ') | title }}
          {% if edu.confidence_score %} · Confidence: {{ edu.confidence_score }}%{% endif %}
        </div>
      </div>
      {% endfor %}
    {% else %}
      <p style="color:#6b7280;font-size:10pt;">No education records found.</p>
    {% endif %}
  </div>

  <!-- FRAUD FLAGS -->
  {% if fraud_flags %}
  <div class="section">
    <div class="section-title">Fraud &amp; Anomaly Indicators</div>
    {% for flag in fraud_flags %}
    <div class="flag-card {% if flag.severity in ['high','critical'] %}flag-{{ flag.severity }}{% endif %}">
      <strong>{{ flag.flag_type | replace('_', ' ') | title }}</strong>
      <span style="color:#6b7280;font-size:9pt;"> ({{ flag.severity | title }})</span><br/>
      {{ flag.description }}
      {% if flag.ai_reasoning %}
      <div style="font-size:9.5pt;color:#6b7280;margin-top:4px;">{{ flag.ai_reasoning }}</div>
      {% endif %}
    </div>
    {% endfor %}
  </div>
  {% endif %}

  <div class="disclaimer">{{ disclaimer }}</div>
</div>
</body>
</html>
"""


async def generate_pdf_report(candidate_id: str) -> str:
    """
    Generate a PDF report for a candidate and store it in MinIO.
    Returns the MinIO storage path.
    """
    from database import AsyncSessionLocal
    from models import Candidate, EmploymentRecord, EducationRecord, FraudFlag, RiskScore
    from sqlalchemy import select
    from services.storage.minio_client import upload_file

    async with AsyncSessionLocal() as db:
        candidate = await db.get(Candidate, uuid.UUID(candidate_id))
        if not candidate:
            raise ValueError(f"Candidate {candidate_id} not found")

        emp_result = await db.execute(
            select(EmploymentRecord).where(EmploymentRecord.candidate_id == candidate.id)
        )
        edu_result = await db.execute(
            select(EducationRecord).where(EducationRecord.candidate_id == candidate.id)
        )
        fraud_result = await db.execute(
            select(FraudFlag).where(FraudFlag.candidate_id == candidate.id)
        )
        risk_result = await db.execute(
            select(RiskScore)
            .where(RiskScore.candidate_id == candidate.id)
            .order_by(RiskScore.calculated_at.desc())
            .limit(1)
        )

        employment   = emp_result.scalars().all()
        education    = edu_result.scalars().all()
        fraud_flags  = fraud_result.scalars().all()
        risk_score   = risk_result.scalar_one_or_none()

    # Build template context
    context = {
        "candidate_name": candidate.full_name,
        "status": candidate.status,
        "generated_at": datetime.utcnow().strftime("%B %d, %Y at %H:%M UTC"),
        "risk_score": risk_score.overall_score if risk_score else 0,
        "risk_level": risk_score.risk_level if risk_score else "unknown",
        "confidence": round((risk_score.confidence * 100) if risk_score else 0),
        "ai_reasoning": risk_score.ai_reasoning if risk_score else "",
        "breakdown": risk_score.score_breakdown if risk_score else {},
        "employment": [
            {
                "company_name": e.company_name,
                "job_title": e.job_title,
                "start_date": e.start_date,
                "end_date": e.end_date,
                "location": e.location,
                "verification_status": e.verification_status,
                "confidence_score": e.confidence_score,
                "notes": e.notes,
            }
            for e in employment
        ],
        "education": [
            {
                "institution_name": e.institution_name,
                "degree": e.degree,
                "field_of_study": e.field_of_study,
                "graduation_year": e.graduation_year,
                "verification_status": e.verification_status,
                "confidence_score": e.confidence_score,
            }
            for e in education
        ],
        "fraud_flags": [
            {
                "flag_type": f.flag_type,
                "severity": f.severity,
                "description": f.description,
                "ai_reasoning": f.ai_reasoning,
            }
            for f in fraud_flags
        ],
        "disclaimer": DISCLAIMER,
    }

    # Render HTML
    try:
        from jinja2 import Environment
        env = Environment(autoescape=True)
        template = env.from_string(HTML_TEMPLATE)
        html_content = template.render(**context)
    except Exception as exc:
        logger.error("Jinja2 render failed: %s", exc)
        raise

    # Convert to PDF
    try:
        import weasyprint
        pdf_bytes = weasyprint.HTML(string=html_content).write_pdf()
    except ImportError:
        logger.warning("WeasyPrint not installed — storing HTML instead")
        pdf_bytes = html_content.encode()

    # Upload to MinIO
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    storage_path = f"reports/{candidate_id}/{timestamp}_report.pdf"
    await upload_file(pdf_bytes, storage_path, "application/pdf")

    logger.info("Generated report for %s → %s (%d bytes)", candidate_id, storage_path, len(pdf_bytes))
    return storage_path
